language: python
python:
 - "3.7"
services:
 - postgresql
before_install:
 - export DATABASE_URL=postgres://postgres@localhost/travisdb
env:
 - DJANGO_VERSION=2.2.4 DB=prostgresql
install:
 - pip install -r requirements.txt 
before script:
 - psql -c "CREATE DATABASE travisdb;" -U postgres
 - python manage.py migrate --noinput
script:
 - python manage.py test

